### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by blueflametuna** [cloudtemple/zabbix_templates#3]
[root@commonnodeappqa10616 zabbix]# /usr/local/bin/zabbix/zabbix_check_redis.py --host localhost --ping
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 552, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 609, in _connect
    raise err
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 597, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

Any ideas what I might be missing here?

**Comment by cloudtemple** [comment]
Sorry for late response, but anyway.
It seems you have IPv6 enabled on your OS, but redis is binded only to 127.0.0.1. Your system resolves localhost as ::1, and then tries to connect to not existent socket. 
You should either bind it explicitly to IPv6 ::1 address, use --host 127.0.0.1, or disable, if not necessary on OS level via sysctl
